name: Bump version
on:
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RELEASE_BRANCHES: release
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.26.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true